using System.Collections.Generic;
using Unity.Cinemachine;
using UnityEngine;
using UnityEngine.Rendering;

public class GeneralCameraRig : CameraRigBase
{
    //CameraRigBase에 전달용
    [SerializeField] private List<CinemachineVirtualCameraBase> _myCameras = new List<CinemachineVirtualCameraBase>();
    protected override IReadOnlyList<CinemachineVirtualCameraBase> CameraCandidates => _myCameras;

    public override void GetInputAxes(List<IInputAxisOwner.AxisDescriptor> axes)
    {
        base.GetInputAxes(axes);
    }

    protected override CinemachineVirtualCameraBase ChooseCurrentCamera(Vector3 worldUp, float deltaTime)
    {
        CinemachineVirtualCameraBase Cam;

        if (LiveChild == null)
            Cam = GetHighestPriorityCamera();
        else
            Cam = (CinemachineVirtualCameraBase)LiveChild;

        return Cam;
    }
}
