using UnityEngine;

public class ProjectileEffect : MonoBehaviour, ISkillEffect
{
    public void Execute(SkillInstance skill, Transform caster, float chargeRatio)
    {
        if (skill.Data.EffectPrefab == null) return;

        Vector3 spawnPos = caster.position + caster.forward + Vector3.up;
        GameObject proj = Instantiate(skill.Data.EffectPrefab, spawnPos, caster.rotation);

        // 투사체에 데미지 정보 전달
        // proj.GetComponent<Projectile>()?.Init(skill.CurrentLevelData.Damage * chargeRatio);
    }
}
