using UnityEngine;
using UnityEngine.InputSystem;

public class CombatSystem : MonoBehaviour
{
    private PlayerStateMachine _playerStateMachine;
    private Animator _animator;
    private float _chargeTimer;

    [SerializeField] private Weapon _currentWeapon; // 현재 장착된 무기

    void Awake()
    {
        _playerStateMachine = GetComponent<PlayerStateMachine>();
        _animator = GetComponent<Animator>();
    }

    public void OnAttackInput(InputAction.CallbackContext context)
    {
        
    }

    void Update()
    {
        if (_playerStateMachine.CurrentState == PlayerState.Charge)
            _chargeTimer += Time.deltaTime;
    }
}